'use client';

import {ArrowUpRight, BookOpen, Check, CircleAlert, GitCompareArrows, ScanText} from 'lucide-react';

export type EvidenceReport = {
  engine_version:string;signature:string;scope:string;
  counts:{missing:number;attention:number;review:number;confirmed:number;documented:number;declared:number;cross_attention:number};
  rows:{id:string;label:string;value:string;status:string;source_type:string;explanation:string;reference_id:string;evidence:{origin:string;reference_id:string;quote:string;page:number|null;document_name:string|null;passage_verified:boolean}[]}[];
  cross_checks:{id:string;title:string;status:string;explanation:string;action_key:string|null;evidence:{key:string;value:string;document_id:string;document_name:string;page:number;evidence:string;sample:boolean;kind?:string;passage_verified?:boolean}[]}[];
};

export function EvidenceOverview({report}:{report:EvidenceReport}) {
  const c=report.counts;
  return <div className="proof-metrics" aria-label="Avancement de la vérification"><div><Check size={18}/><strong>{c.confirmed}<small>/{report.rows.length}</small></strong><span>rubriques confirmées</span></div><div><ScanText size={18}/><strong>{c.documented}</strong><span>rubriques avec une pièce source</span></div><div><BookOpen size={18}/><strong>{c.declared}</strong><span>rubriques déclarées</span></div><div className={c.cross_attention+c.attention+c.missing?'has-alert':''}><CircleAlert size={18}/><strong>{c.cross_attention+c.attention+c.missing}</strong><span>points à résoudre</span></div></div>;
}

export default function EvidenceReportView({report,caseId,disabled=false,onRetain,expanded=false}:{report:EvidenceReport;caseId:string;disabled?:boolean;onRetain?:(documentId:string)=>void;expanded?:boolean}) {
  const retained=report.rows.find(r=>r.id==='company_id')?.value||'';
  return <section className="panel proof-panel"><div className="panel-heading"><div><div className="eyebrow">COMPRENDRE CHAQUE CONTRÔLE</div><h2>Ce que disent les pièces</h2></div><GitCompareArrows size={23}/></div>
    <div className="proof-checks">{report.cross_checks.length?report.cross_checks.map(check=><article key={check.id} className={'proof-check '+check.status}><div className="proof-check-heading"><span className={'badge '+(check.status==='attention'?'amber':check.status==='supported'?'green':'blue')}>{check.status==='attention'?'À résoudre':check.status==='supported'?'Concordance':'Contexte'}</span><h3>{check.title}</h3></div><p>{check.explanation}</p>{check.action_key&&<p className="proof-retained">Dans le formulaire : <strong>{retained||'Non renseigné'}</strong></p>}<div className="proof-documents">{check.evidence.map((e,i)=>{const kindLabel:Record<string,string>={registry:'EXTRAIT DE REGISTRE',decision:'DÉCISION DE TRANSFERT',declaration:'DÉCLARATION',other:'DOCUMENT'};const fieldLabel=e.key==='current_address'?'SIÈGE ACTUEL':e.key==='new_address'?'SIÈGE PROPOSÉ':'IDENTIFIANT';return <div className="proof-document" key={e.document_id+i}><small>{fieldLabel} · {(e.kind && kindLabel[e.kind])||'PIÈCE'}</small><strong dir="auto">{check.action_key&&retained?Array.from(e.value).map((char,index)=>char!==retained[index]?<mark key={index}>{char}</mark>:<span key={index}>{char}</span>):e.value}</strong><blockquote dir="auto">{e.evidence}</blockquote><a href={`/api/cases/${caseId}/documents/${e.document_id}/file#page=${e.page}`} target="_blank" rel="noreferrer">{e.document_name} · p. {e.page}<ArrowUpRight size={12}/></a>{onRetain&&check.status==='attention'&&check.action_key==='company_id'&&e.value!==retained&&<button className="btn small secondary" disabled={disabled} onClick={()=>onRetain(e.document_id)}>Retenir cet identifiant</button>}</div>})}</div></article>):<div className="soft-note">Ajoutez des pièces de la société pour comparer leurs informations. Les contrôles ci-dessous portent sur les rubriques disponibles.</div>}</div>
    <details className="proof-ledger" open={expanded||undefined}><summary><BookOpen size={16}/>Ouvrir la traçabilité des {report.rows.length} rubriques</summary><div>{report.rows.map(row=><article key={row.id}><div><strong>{row.label}</strong><span className={'badge '+(row.status==='confirmed'?'green':row.status==='attention'?'amber':'neutral')}>{({confirmed:'Confirmé',review:'À relire',missing:'Manquant',attention:'À vérifier'})[row.status]}</span></div><p dir="auto">{row.value||'Non renseigné'}</p><small>{row.explanation}</small>{row.evidence.map((e,i)=><blockquote key={i} dir="auto">{e.quote}{e.origin==='document'?<a href={`/api/cases/${caseId}/documents/${e.reference_id}/file#page=${e.page}`} target="_blank" rel="noreferrer">{e.document_name} · p. {e.page} · {e.passage_verified?'passage retrouvé':'passage à vérifier'}<ArrowUpRight size={12}/></a>:<span>Déclaration de l’utilisateur</span>}</blockquote>)}</article>)}</div></details><p className="proof-scope">{report.scope}</p>
  </section>;
}
