'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {CheckCheck, CircleAlert, Clock3, FileText, Inbox, QrCode, ShieldCheck} from 'lucide-react';
import {api} from '@/lib/types';
import EvidenceReportView,{EvidenceOverview,EvidenceReport} from './evidence-report';

type Handoff={case_id:string;company:string;status:string;sample:boolean;submission_id:string;submitted_at:string;revision:number;signature:string;report:EvidenceReport;qr_url?:string;decision:null|{action:string;note:string;check_ids:string[];at:string};history:{submission_id:string;signature:string;decision:null|{note:string}}[]};
const labels:Record<string,string>={submitted:'À examiner',reviewed:'Revue terminée',correction_requested:'Correction demandée'};

export default function InstitutionalReview({onChanged}:{onChanged:()=>Promise<void>}) {
  const [queue,setQueue]=useState<Handoff[]>([]);const [selected,setSelected]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [updated,setUpdated]=useState('');
  useEffect(()=>{let active=true,pending=false;async function poll(){if(pending||document.hidden)return;pending=true;try{const data=await api<Handoff[]>('/institution/queue');if(active){setQueue(data);setUpdated(new Date().toLocaleTimeString('fr-TN'));}}catch(e){if(active)setError(e instanceof Error?e.message:'File indisponible.');}finally{pending=false;}}poll();const timer=setInterval(poll,5000);return()=>{active=false;clearInterval(timer);};},[]);
  const current=queue.find(c=>c.submission_id===selected)||queue.find(c=>c.status==='submitted')||queue[0];
  async function decide(action:string,note:string,checkIds:string[]){if(!current||busy)return;setBusy(true);setError('');try{await api(`/cases/${current.case_id}/rne/review`,{method:'POST',body:JSON.stringify({submission_id:current.submission_id,action,note,check_ids:checkIds})});setQueue(await api<Handoff[]>('/institution/queue'));await onChanged();}catch(e){setError(e instanceof Error?e.message:'La décision n’a pas été enregistrée.');}finally{setBusy(false);}}
  return <><div className="page-heading"><div><div className="eyebrow">PORTAIL INSTITUTIONNEL · SIMULATION</div><h1>Examiner, avec les preuves.</h1><p>Les informations, leurs sources et les confirmations dans une même vue.</p></div><Link href="/impact" className="btn secondary"><Clock3 size={17}/>The Agency Benefit</Link></div>
    <div className="institution-status"><span className="mini-status"><span className="status-dot"/>File synchronisée toutes les 5 secondes</span><small>{updated?'Dernière lecture : '+updated:'Connexion…'}</small></div>{error&&<p className="error-banner" role="alert">{error}</p>}
    {!queue.length?<section className="panel institution-empty"><Inbox size={35}/><h2>Aucune déclaration transmise</h2><p>Préparez un F005, résolvez les écarts puis transmettez-le à la revue locale.</p><Link className="btn primary" href="/declaration">Ouvrir la préparation</Link></section>:<><div className="institution-queue">{queue.map(c=><button key={c.submission_id} className={'panel institution-ticket '+(c.submission_id===current?.submission_id?'selected':'')} onClick={()=>setSelected(c.submission_id)}><span className={'badge '+(c.status==='reviewed'?'green':c.status==='submitted'?'blue':'amber')}>{labels[c.status]}</span><strong>{c.company}</strong><small>{c.submission_id}{c.sample?' · données fictives':''}</small></button>)}</div>
      {current&&<><EvidenceOverview report={current.report}/><div className="institution-body"><div><EvidenceReportView report={current.report} caseId={current.case_id}/><details className="panel institution-audit"><summary><ShieldCheck size={17}/>Version transmise et historique</summary><p>Version {current.revision} · {current.submission_id}</p><p>Transmise le {new Date(current.submitted_at).toLocaleString('fr-TN')}</p><small>Empreinte du contenu, utile pour identifier une version ; elle ne certifie pas l’authenticité des pièces.</small><code>{current.signature}</code>{current.history.map(h=><article key={h.submission_id}><strong>{h.submission_id}</strong><p>{h.decision?.note||'Version antérieure'}</p></article>)}</details></div><DecisionPanel key={current.submission_id+current.status} current={current} busy={busy} decide={decide}/></div></>}
    </>}
  </>;
}

function DecisionPanel({current,busy,decide}:{current:Handoff;busy:boolean;decide:(action:string,note:string,ids:string[])=>Promise<void>}) {
  const [note,setNote]=useState('');const [ids,setIds]=useState<string[]>([]);
  return <aside className="panel institution-decision"><ShieldCheck size={26}/><h2>Revue humaine</h2><p>L'IA prépare les informations. L'agent conserve la décision et la motive.</p><a className="btn secondary full" href={`/api/cases/${current.case_id}/rne/submissions/${current.submission_id}/pdf`} target="_blank" rel="noreferrer"><FileText size={16}/>Consulter le F005</a>{current.qr_url&&<div className="qr-block"><div className="qr-label"><QrCode size={16}/>Fiche de suivi vérifiable</div><img src={current.qr_url} alt={'QR code de vérification ' + current.submission_id} className="qr-image"/><a className="text-link" href={'/verify/' + current.submission_id} target="_blank" rel="noreferrer">Ouvrir la fiche</a><small>Scannez depuis un téléphone pour vérifier l'état du dossier.</small></div>}{current.decision?<div className="soft-note"><strong>{labels[current.status]}</strong><p>{current.decision.note}</p><Link href={`/dossiers/${current.case_id}/declaration`} className="text-link">Retour au dossier entreprise</Link></div>:<><fieldset disabled={busy||current.status!=='submitted'}><legend>Rubriques concernées par une correction</legend>{current.report.rows.map(row=><label key={row.id}><input type="checkbox" checked={ids.includes(row.id)} onChange={e=>setIds(old=>e.target.checked?[...old,row.id]:old.filter(k=>k!==row.id))}/>{row.label}</label>)}</fieldset><label className="form-label">Observation<textarea rows={4} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Précisez ce qui doit être corrigé ou ce qui a été examiné." disabled={busy}/></label><button className="btn secondary full" disabled={busy||!ids.length||note.trim().length<5||current.status!=='submitted'} onClick={()=>decide('request_correction',note,ids)}><CircleAlert size={16}/>Demander une correction ciblée</button><button className="btn primary full" disabled={busy||note.trim().length<5||current.status!=='submitted'} onClick={()=>decide('reviewed',note,[])}><CheckCheck size={16}/>Terminer la revue de préparation</button></>}<small>Simulation locale. Aucun agrément, dépôt ou récépissé officiel n'est émis.</small></aside>;
}
