'use client';

import {useEffect, useRef, useState, type ReactNode} from 'react';
import Link from 'next/link';
import {ArrowDownToLine, ArrowLeft, ArrowRight, ArrowUpRight, BookOpen, Check, CheckCheck, ChevronRight, Clock3, FileText, Flag, FolderOpen, LoaderCircle, MessageCircle, Search, Send, ShieldCheck, Sparkles, Upload, X} from 'lucide-react';
import {api, type Answer, type Case, type Health} from '@/lib/types';
import type {FormCatalog, FormDraft, FormField, OcrBatch} from '@/lib/form-types';
import {useFormDraft} from '@/lib/use-form-draft';
import JourneyChat, {ReviewBrief} from './journey-chat';

type ReviewCase = Case & {submitted_at?:string; flagged?:boolean; last_review?:{action:string;note:string;at:string;checklist:string[]}};
const labels:Record<string,string> = {draft:'En préparation', submitted:'En attente de revue', correction_requested:'Correction demandée', reviewed:'Revue validée'};
const stamp = (value:string) => new Intl.DateTimeFormat('fr-TN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
const applicable = (catalog:FormCatalog, draft:FormDraft) => catalog.fields.filter(f=>!f.visible_when||f.visible_when.some(k=>draft.modifications.includes(k)));
const required = (f:FormField,draft:FormDraft) => f.required||f.required_when?.some(k=>draft.modifications.includes(k));
const isLocked = (c:Case) => ['submitted','reviewed'].includes(c.status);

function Status({c}:{c:ReviewCase}) {
  return <span className={'live-status '+c.status}><span/>{labels[c.status]||c.status}{c.flagged&&' · Signalé'}</span>;
}

function Progress({c,draft}:{c:ReviewCase;draft:FormDraft}) {
  const stage=c.status==='reviewed'?3:c.status==='submitted'||c.status==='correction_requested'?2:draft.has_pdf?1:0;
  const items=['Préparation du F005','PDF préparé','Examen du dossier','Revue validée'];
  return <section className="live-progress"><span className="live-eyebrow">Suivi de la démarche</span><ol>{items.map((label,i)=><li key={label} className={i<stage?'done':i===stage?'current':''}><span>{i<stage?<Check size={13}/>:i+1}</span><div>{label}{i===stage&&<small>{c.status==='correction_requested'?'Correction attendue de l’entreprise':c.status==='reviewed'?'Terminée dans le prototype':'Étape actuelle'}</small>}</div></li>)}</ol><p><ShieldCheck size={14}/>Revue locale · aucun dépôt officiel au RNE.</p></section>;
}

function Packet({c,draft,catalog,onField,onModifications}:{c:ReviewCase;draft:FormDraft;catalog:FormCatalog;onField?:(key:string,value:string)=>void;onModifications?:(keys:string[])=>void}) {
  const [tab,setTab]=useState('fields');
  const fields=applicable(catalog,draft);
  const needed=fields.filter(f=>required(f,draft));
  const complete=needed.filter(f=>draft.fields[f.key]?.trim()&&!draft.errors[f.key]).length;
  return <section className="live-packet">
    <header className="live-packet-heading"><div><span className="live-eyebrow">Dossier partagé</span><h2>{c.company}</h2><p>Déclaration de modification · RNE F005</p></div><FileText size={27}/></header>
    <div className="live-packet-tabs" role="tablist" aria-label="Contenu du dossier">{[['fields','Formulaire'],['documents','Pièces',c.documents.length],['history','Historique',c.events.length]].map(([key,label,count])=><button key={key} role="tab" aria-selected={tab===key} onClick={()=>setTab(String(key))}>{label}{count!==undefined&&<span>{count}</span>}</button>)}</div>
    <div className="live-packet-content">
      {tab==='fields'&&<><div className="live-completion"><span><Sparkles size={14}/> Formulaire intelligent</span><strong>{complete}/{needed.length} champs requis</strong></div><div className="live-meter"><span style={{width:`${needed.length?complete/needed.length*100:0}%`}}/></div>
        {onModifications&&<details className="journey-manual-mods"><summary>Ajuster les modifications déclarées</summary>{catalog.modifications.map(m=><label key={m.key}><input type="checkbox" checked={draft.modifications.includes(m.key)} onChange={e=>onModifications(e.target.checked?[...draft.modifications,m.key]:draft.modifications.filter(k=>k!==m.key))}/>{m.label}</label>)}</details>}<div className="live-mod-summary">{catalog.modifications.filter(m=>draft.modifications.includes(m.key)).map(m=><span key={m.key}>{m.label}</span>)}{!draft.modifications.length&&<span>Modification à choisir</span>}</div>
        <div className="live-field-grid">{fields.map(f=><div className="live-field" key={f.key}><label htmlFor={'packet-'+f.key}>{f.label}{required(f,draft)?' *':''}</label><small lang="ar" dir="rtl">{f.arabic}</small>{onField?<input id={'packet-'+f.key} type={f.input_type} value={draft.fields[f.key]||''} placeholder={f.example} maxLength={f.max_length} onChange={e=>onField(f.key,e.target.value)} disabled={draft.same_person&&['nom_declarant','identite_declarant'].includes(f.key)} dir="auto"/>:<p dir="auto">{draft.fields[f.key]||'Non renseigné'}</p>}{draft.fields[f.key]&&draft.errors[f.key]&&<small className="live-error">{draft.errors[f.key]}</small>}{draft.provenance[f.key]?<details className="live-proof"><summary><BookOpen size={12}/>Pièce source · p. {draft.provenance[f.key].page}</summary><blockquote>{draft.provenance[f.key].evidence}</blockquote><a href={`/api/cases/${c.id}/documents/${draft.provenance[f.key].document_id}/file`} target="_blank" rel="noreferrer">Ouvrir la pièce <ArrowUpRight size={12}/></a></details>:draft.fields[f.key]?<small className="live-origin">Saisie déclarative</small>:null}</div>)}</div>
        <a className="live-source" href={catalog.sources.form?.url} target="_blank" rel="noreferrer"><BookOpen size={14}/>Formulaire officiel et notice RNE<ArrowUpRight size={14}/></a>
      </>}
      {tab==='documents'&&<>{!c.documents.length&&<div className="live-empty"><FolderOpen size={30}/><p>Aucune pièce ajoutée pour le moment.</p></div>}{c.documents.map(d=><a className="live-doc" href={`/api/cases/${c.id}/documents/${d.id}/file`} target="_blank" rel="noreferrer" key={d.id}><FileText size={22}/><div><strong>{d.name}</strong><small>{d.sample?'Exemple fictif':d.status==='extracted'?'Lecture terminée':'Analyse à effectuer'} · {d.pages.length} page(s)</small></div><ArrowUpRight size={15}/></a>)}<p className="live-footnote">Les originaux sont conservés avec les informations confirmées.</p></>}
      {tab==='history'&&<ol className="live-history">{[...c.events].reverse().map(e=><li key={e.id}><span/><div><strong>{e.label}</strong><small>{stamp(e.at)} · {e.actor}</small>{e.detail&&<p dir="auto">{e.detail}</p>}</div></li>)}</ol>}
    </div>
    {draft.has_pdf&&<footer className="live-downloads"><a href={`/api/cases/${c.id}/f005/pdf`}><ArrowDownToLine size={15}/>F005 PDF</a><a href={`/api/cases/${c.id}/export`}><ArrowDownToLine size={15}/>Dossier complet</a></footer>}
  </section>;
}

export default function LiveWorkflow({c,health,onUpdate}:{c:ReviewCase;health:Health|null;onUpdate:()=>Promise<void>}) {
  const {draft,loading,status,error,setError,change,flush,commit,recovery,restore,discard}=useFormDraft(c.id);
  const [catalog,setCatalog]=useState<FormCatalog|null>(null);
  const [value,setValue]=useState(''),[busy,setBusy]=useState(''),[reviewed,setReviewed]=useState(false);
  const [batch,setBatch]=useState<OcrBatch|null>(null),[choices,setChoices]=useState<Record<string,number>>({});
  const [kind,setKind]=useState('auto');
  const upload=useRef<HTMLInputElement>(null);
  const locked=isLocked(c);
  useEffect(()=>{let active=true;api<FormCatalog>('/f005/catalog').then(data=>{if(active)setCatalog(data);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[setError]);
  useEffect(()=>{if(!locked)return;let active=true;api<FormDraft>(`/cases/${c.id}/f005`).then(d=>{if(active)commit(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[c.id,c.updated_at,locked,commit,setError]);
  const fields=catalog?applicable(catalog,draft):[];
  const next=fields.find(f=>required(f,draft)&&(!draft.fields[f.key]?.trim()||draft.errors[f.key]));
  async function run(name:string,fn:()=>Promise<void>){if(busy)return;setBusy(name);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'La demande a échoué.');}finally{setBusy('');}}
  function updateField(key:string,text:string){const provenance={...draft.provenance};delete provenance[key];change({fields:{...draft.fields,[key]:text},provenance});setReviewed(false);}
  async function read(file:File){await run('ocr',async()=>{await flush();const data=new FormData();data.append('file',file);data.append('kind',kind);const result=await api<OcrBatch>(`/cases/${c.id}/f005/ocr`,{method:'POST',body:data});setChoices({});setBatch(result);await onUpdate();});if(upload.current)upload.current.value='';}
  async function apply(){await run('apply',async()=>{if(!batch)return;const fields={...draft.fields},provenance={...draft.provenance};Object.entries(choices).forEach(([key,index])=>{const candidate=batch.candidates[index];let value=candidate.value.trim();if(['identifiant_unique','rib','identite_representant','identite_declarant'].includes(key))value=value.replace(/[\s-]/g,'');if(key==='date'&&/^\d{2}\/\d{2}\/\d{4}$/.test(value)){const [d,m,y]=value.split('/');value=`${y}-${m}-${d}`;}fields[key]=value;if(batch.document_id)provenance[key]={document_id:batch.document_id,page:candidate.page,evidence:candidate.evidence,value};});change({fields,provenance});await flush();setReviewed(false);setBatch(null);await onUpdate();});}
  if(loading||!catalog)return <div className="live-empty">{error||'Ouverture de votre démarche…'}</div>;
  return <div className="live-workspace">
    <div className="live-page-heading"><div><span className="live-eyebrow">Votre espace RNE</span><h1>Une conversation.<br/><em>Un dossier qui avance.</em></h1><p>Vos informations, vos pièces et votre suivi, au même endroit.</p></div><Link className="live-quiet" href="/agence"><ShieldCheck size={17}/>Espace agent <ArrowUpRight size={15}/></Link></div>
    <div className="live-service-tabs"><span className="active">Modification d’entreprise</span><span>RNE F005</span><span className="journey-shared-label">Conversation et formulaire synchronisés</span></div>
    {error&&<div role="alert" className="live-alert">{error}<button onClick={()=>void run('save',async()=>{await flush();await onUpdate();})}>Réessayer</button></div>}
    {recovery&&<div className="live-alert">Une saisie non enregistrée est disponible.<button onClick={restore}>Restaurer</button><button onClick={discard}>Ignorer</button></div>}
    {c.last_review&&<div className={'live-review-note '+c.status}><MessageCircle size={18}/><div><strong>{c.last_review.action==='flag'?'Observation de l’agent':labels[c.status]}</strong><p>{c.last_review.note}</p><small>{stamp(c.last_review.at)}</small></div></div>}
    <section className="live-console"><header className="live-console-heading"><div className="live-workflow-icon"><FileText size={21}/></div><div><span className="live-eyebrow">Démarche en cours · {c.id}</span><h2>Déclaration de modification</h2></div><Status c={c}/></header>
      <div className="live-columns"><JourneyChat c={c} draft={draft} health={health} next={next} flush={flush} onRefresh={onUpdate} onCommit={async d=>{commit(d);setReviewed(false);await onUpdate();}}>
          {!locked&&<><div className="live-upload"><select value={kind} onChange={e=>setKind(e.target.value)} aria-label="Type de pièce"><option value="auto">Identifier les informations automatiquement</option><option value="registry">Extrait RNE / pièce fiscale</option><option value="representative">Identité du représentant</option><option value="declarant">Identité du déclarant</option><option value="bank">Document bancaire</option><option value="form">Formulaire existant</option></select><button disabled={!!busy} onClick={()=>upload.current?.click()}><Upload size={15}/>{busy==='ocr'?'Lecture…':'Joindre une pièce'}</button><input hidden ref={upload} type="file" accept=".pdf,.png,.jpg,.jpeg,.txt" onChange={e=>{if(e.target.files?.[0])void read(e.target.files[0]);}}/></div>{c.documents.some(d=>!d.sample)&&<details className="journey-existing"><summary>Reprendre une pièce déjà ajoutée</summary>{c.documents.filter(d=>!d.sample).map(d=><button key={d.id} disabled={!!busy} onClick={()=>void run('ocr',async()=>{await flush();const result=await api<OcrBatch>(`/cases/${c.id}/f005/import`,{method:'POST',body:JSON.stringify({document_id:d.id,kind})});setChoices({});setBatch(result);await onUpdate();})}><FileText size={13}/>{d.name}</button>)}</details>}<small className="journey-upload-hint">PDF, images ou TXT · 8 Mo. Les valeurs extraites restent à confirmer.</small></>}
          <small><span className={'live-save '+status}/>{status==='saved'?'Dossier enregistré':status==='error'?'Enregistrement à réessayer':'Enregistrement…'}</small>
        </JourneyChat><Packet c={c} draft={draft} catalog={catalog} onField={!locked?updateField:undefined} onModifications={!locked?keys=>{change({modifications:keys});setReviewed(false);}:undefined}/><aside className="live-rail"><Progress c={c} draft={draft}/><section className="live-next"><span className="live-eyebrow">Votre prochaine action</span>{!locked?<><p>{draft.has_pdf?'Votre PDF est prêt. Transmettez le dossier à la revue locale.':'Relisez vos informations et préparez la déclaration.'}</p>{!draft.has_pdf&&<><label className="live-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>J’ai vérifié les informations avec mes pièces.</label><button className="live-primary" disabled={!!busy||!reviewed||!draft.ready||status!=='saved'} onClick={()=>void run('pdf',async()=>{const saved=await flush();const d=await api<FormDraft>(`/cases/${c.id}/f005/generate`,{method:'POST',body:JSON.stringify({revision:saved.revision,reviewed:true})});commit(d);await onUpdate();})}><FileText size={15}/>{busy==='pdf'?'Préparation…':'Préparer le PDF'}</button></>}{draft.has_pdf&&<button className="live-primary" disabled={!!busy||!c.can_submit||status!=='saved'} onClick={()=>void run('submit',async()=>{await flush();await api(`/cases/${c.id}/submit`,{method:'POST'});await onUpdate();})}><Send size={15}/>Transmettre à la revue</button>}{c.checks.open_count>0&&<Link className="live-warning-link" href={`/dossiers/${c.id}/verification`}>{c.checks.open_count} écart(s) à confirmer <ArrowRight size={14}/></Link>}{c.checks.pending_documents.length>0&&<Link className="live-warning-link" href={`/dossiers/${c.id}/documents`}>{c.checks.pending_documents.length} pièce(s) à analyser <ArrowRight size={14}/></Link>}</>:<p>Consultez le suivi et les observations de votre dossier.</p>}<small>Le PDF généré reste à signer. La revue du prototype ne vaut pas approbation officielle.</small></section></aside></div>
    </section>
    {batch&&<OcrModal onClose={()=>setBatch(null)}><header><div><span className="live-eyebrow">Lecture de pièce</span><h2 id="ocr-review-title">Confirmez les informations extraites.</h2></div><button aria-label="Fermer" onClick={()=>setBatch(null)}><X size={21}/></button></header><p>{batch.name} · {batch.method}</p>{batch.warnings?.map(w=><p className="live-alert" key={w}>{w}</p>)}{!batch.candidates.length&&<p>Aucun champ F005 à reprendre. Les faits extraits des pièces restent disponibles pour les contrôles du dossier.</p>}{batch.candidates.map((candidate,i)=><label className="live-candidate" key={i}><input type="checkbox" checked={choices[candidate.key]===i} onChange={e=>setChoices(old=>{const copy={...old};if(e.target.checked)copy[candidate.key]=i;else delete copy[candidate.key];return copy;})}/><span><strong>{catalog.fields.find(f=>f.key===candidate.key)?.label||candidate.key} : {candidate.value}</strong><small>Page {candidate.page} · {candidate.evidence}</small>{draft.fields[candidate.key]&&draft.fields[candidate.key]!==candidate.value&&<small className="live-error">Remplacera : {draft.fields[candidate.key]}</small>}</span></label>)}<footer><button className="live-quiet" onClick={()=>setBatch(null)}>Conserver sans reprendre</button><button className="live-primary" disabled={!!busy||!Object.keys(choices).length} onClick={()=>void apply()}>Confirmer {Object.keys(choices).length} valeur(s)</button></footer></OcrModal>}
  </div>;
}

export function AgencyWorkspace({cases,onUpdate}:{cases:ReviewCase[];onUpdate:()=>Promise<void>}) {
  const [query,setQuery]=useState(''),[filter,setFilter]=useState('submitted'),[selected,setSelected]=useState('');
  const [catalog,setCatalog]=useState<FormCatalog|null>(null),[error,setError]=useState('');
  useEffect(()=>{let active=true;api<FormCatalog>('/f005/catalog').then(d=>{if(active)setCatalog(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
  const all=cases.filter(c=>c.status!=='draft'||c.submitted_at);
  const filtered=all.filter(c=>(filter==='all'||(filter==='flagged'?c.flagged:c.status===filter))&&(c.company+' '+c.id).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(a.submitted_at||a.updated_at).localeCompare(b.submitted_at||b.updated_at));
  const current=all.find(c=>c.id===selected);
  return <div className="live-workspace agency-workspace"><div className="live-page-heading"><div><span className="live-eyebrow">Espace agent · Simulation RNE</span><h1>Chaque dossier.<br/><em>Une décision éclairée.</em></h1><p>Pièces, informations et observations réunies pour votre revue.</p></div><Link className="live-quiet" href="/dossiers"><ArrowLeft size={16}/>Espace entreprise</Link></div><div className="live-agency-metrics">{[['À examiner',all.filter(c=>c.status==='submitted').length],['Corrections attendues',all.filter(c=>c.status==='correction_requested').length],['Revues validées',all.filter(c=>c.status==='reviewed').length],['Signalés',all.filter(c=>c.flagged).length]].map(([label,count])=><div key={label}><span>{label}</span><strong>{String(count).padStart(2,'0')}</strong></div>)}</div><p className="live-footnote"><ShieldCheck size={14}/>Espace de démonstration partagé, sans authentification d’agent ni connexion officielle au RNE. Actualisation toutes les 5 secondes.</p>
    {error&&<p role="alert" className="live-alert">{error}</p>}
    {current&&catalog?<><button className="live-back" onClick={()=>setSelected('')}><ArrowLeft size={16}/>Retour à la file de revue</button><AgencyReview key={current.id} c={current} catalog={catalog} onUpdate={onUpdate}/></>:<section className="live-queue"><header><h2>File de revue <span>{filtered.length}</span></h2><label><Search size={16}/><input aria-label="Rechercher dans la file" placeholder="Entreprise ou référence…" value={query} onChange={e=>setQuery(e.target.value)}/></label></header><div className="live-queue-tabs">{[['submitted','À examiner'],['correction_requested','Corrections'],['reviewed','Validés'],['flagged','Signalés'],['all','Tous']].map(([key,label])=><button key={key} onClick={()=>setFilter(key)} className={filter===key?'active':''}>{label}</button>)}</div><div className="live-queue-scroll"><table><thead><tr><th>Entreprise / Dossier</th><th>État</th><th>Pièces</th><th>Transmis le</th><th>Action</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><strong>{c.company}</strong><small>{c.id} · RNE F005</small></td><td><Status c={c}/></td><td>{c.documents.length}</td><td>{stamp(c.submitted_at||c.updated_at)}</td><td><button onClick={()=>setSelected(c.id)} disabled={!catalog}>Examiner <ChevronRight size={16}/></button></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="live-empty"><InboxIcon/><h3>Aucun dossier dans cette file.</h3><p>Les dossiers apparaissent ici après leur transmission depuis l’espace entreprise.</p></div>}</section>}
  </div>;
}

function InboxIcon(){return <FolderOpen size={32}/>;}

function AgencyReview({c,catalog,onUpdate}:{c:ReviewCase;catalog:FormCatalog;onUpdate:()=>Promise<void>}) {
  const [draft,setDraft]=useState<FormDraft|null>(null),[error,setError]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[checklist,setChecklist]=useState<string[]>([]);
  useEffect(()=>{let active=true;api<FormDraft>(`/cases/${c.id}/f005`).then(d=>{if(active)setDraft(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[c.id,c.updated_at,c.form.revision]);
  useEffect(()=>{setChecklist([]);},[c.updated_at]);
  async function decide(action:string){setBusy(true);setError('');try{await api(`/cases/${c.id}/review`,{method:'POST',body:JSON.stringify({action,note,checklist,expected_updated_at:c.updated_at})});setNote('');await onUpdate();}catch(e){setError(e instanceof Error?e.message:'Action indisponible.');await onUpdate().catch(()=>{});}finally{setBusy(false);}}
  if(!draft)return <div className="live-empty">{error||'Chargement du dossier…'}</div>;
  return <section className="live-console"><header className="live-console-heading"><div className="live-workflow-icon"><ShieldCheck size={21}/></div><div><span className="live-eyebrow">Revue du dossier · {c.id}</span><h2>{c.company}</h2></div><Status c={c}/></header>{error&&<p role="alert" className="live-alert">{error}</p>}<div className="live-columns agency-columns"><section className="live-review-panel"><span className="live-eyebrow">Contrôle par l’agent</span><h2>Vérifier, puis décider.</h2><p>Consultez les pièces et leurs sources avant de confirmer les points de contrôle.</p><ReviewBrief c={c}/><div className="live-checklist">{[['identity','Identité et représentation','Identifiants, représentant et déclarant vérifiés avec les pièces.'],['documents','Pièces justificatives','Pièces requises pour la formalité consultées et vérifiées.'],['declaration','Déclaration F005','Rubriques, modifications et PDF relus.']].map(([key,title,description])=><label className="live-check" key={key}><input type="checkbox" disabled={busy||c.status!=='submitted'} checked={checklist.includes(key)} onChange={e=>setChecklist(old=>e.target.checked?[...old,key]:old.filter(k=>k!==key))}/><span><strong>{title}</strong><small>{description}</small></span></label>)}</div><div className="live-review-controls"><span><CheckCheck size={16}/>{c.checks.open_count} écart(s) non confirmé(s)</span><span><FileText size={16}/>{draft.has_pdf?'PDF à jour':'PDF non préparé'}</span><span><Clock3 size={16}/>{c.checks.pending_documents.length} analyse(s) en attente</span></div>{c.checks.issues.map(issue=><details className="live-proof" key={issue.key}><summary>{issue.label} · {issue.resolved?'Confirmé':'À résoudre'}</summary>{issue.evidence.map((e,i)=><blockquote key={i}>{e.document_name} · p. {e.page}<br/>{e.evidence}</blockquote>)}{issue.confirmation&&<p>Valeur retenue : {issue.confirmation.value}</p>}</details>)}<a className="live-source" href={catalog.sources.procedures?.url} target="_blank" rel="noreferrer"><BookOpen size={14}/>Vérifier les exigences de la formalité <ArrowUpRight size={14}/></a>
      {c.status==='submitted'?<div className="live-decision"><label htmlFor="review-note">Observation de revue <span>obligatoire</span></label><textarea id="review-note" value={note} onChange={e=>setNote(e.target.value)} placeholder="Précisez les vérifications effectuées ou les corrections attendues…" maxLength={2000} disabled={busy}/><small>Cette observation sera visible par l’entreprise et conservée dans l’historique.</small><button className="live-primary" disabled={busy||!note.trim()||checklist.length!==3||(draft.revision>0&&!c.can_submit)} onClick={()=>void decide('reviewed')}><CheckCheck size={16}/>Valider la revue locale</button><button className="live-secondary" disabled={busy||!note.trim()} onClick={()=>void decide('request_correction')}><MessageCircle size={16}/>Demander une correction</button><button className="live-quiet" disabled={busy||!note.trim()} onClick={()=>void decide('flag')}><Flag size={15}/>Signaler pour suivi</button></div>:<div className="live-review-note"><div><strong>{labels[c.status]}</strong><p>{c.last_review?.note}</p></div></div>}
    </section><Packet c={c} draft={draft} catalog={catalog}/><aside className="live-rail"><Progress c={c} draft={draft}/><section className="live-next"><span className="live-eyebrow">Traçabilité</span><p>Chaque décision conserve son observation et son horodatage dans le dossier partagé.</p><Link className="live-quiet" href={`/dossiers/${c.id}/conversation`}>Voir le côté entreprise <ArrowUpRight size={14}/></Link></section></aside></div></section>;
}

function OcrModal({children,onClose}:{children:ReactNode;onClose:()=>void}) {
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{dialog.current?.showModal();},[]);
  return <dialog ref={dialog} className="live-ocr-review" aria-labelledby="ocr-review-title" onCancel={onClose}>{children}</dialog>;
}
