'use client';

import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {ArrowDownToLine,ArrowRight,ArrowUpRight,BookOpen,Building2,Check,CheckCheck,ChevronDown,ChevronRight,CircleAlert,Clock3,FileCheck2,FileText,FolderOpen,House,Inbox,LoaderCircle,Menu,MessageCircle,Plus,Search,Send,ShieldCheck,Sparkles,UploadCloud,X} from 'lucide-react';
import {api,Case,Document,Health,Issue,Source} from '@/lib/types';
import DocumentReview from './document-review';
import CorrectionNotice from './correction-notice';
import RneConversation from './rne-conversation';

const statusNames:Record<string,string>={draft:'À compléter',submitted:'À examiner',correction_requested:'Correction demandée',reviewed:'Revue terminée'};
const fieldNames:Record<string,string>={company_name:'Dénomination',company_id:'Identifiant',current_address:'Adresse actuelle',new_address:'Nouvelle adresse',representative:'Représentant',decision_date:'Date de décision'};
const date=(value:string)=>new Intl.DateTimeFormat('fr-TN',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
const firstFact=(c:Case,key:string)=>{const field=c.prepared_fields.find(f=>f.key===key);return field?.state==='conflict'?'Écart à confirmer':field?.value||'Non renseigné';};

function Status({status}:{status:string}) {return <span className={'badge '+(status==='reviewed'?'green':status==='submitted'?'blue':'amber')}><span className="status-dot"/>{statusNames[status]||status}</span>;}
function Steps({c,step}:{c:Case;step:number}) {return <div className="steps">{['Documents','Vérification','Préparation','Revue'].map((label,i)=><Link key={label} href={i===3?`/agence/${c.id}`:`/dossiers/${c.id}/${['documents','verification','preparation'][i]}`} className={'step '+(i===step?'current':i<step?'done':'')}><span className="step-num">{i<step?<Check size={14}/>:i+1}</span><span>{label}</span>{i<3&&<span className="step-line"/>}</Link>)}</div>;}
function Empty({title,body}:{title:string;body:string}) {return <div className="empty"><Inbox size={36}/><h3>{title}</h3><p>{body}</p></div>;}

export default function Workspace(){
  const pathname=usePathname(); const router=useRouter();
  const [cases,setCases]=useState<Case[]>([]); const [health,setHealth]=useState<Health|null>(null); const [sources,setSources]=useState<Source[]>([]);
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [busy,setBusy]=useState(''); const [notice,setNotice]=useState('');
  const [selected,setSelected]=useState('DOS-026'); const [mobile,setMobile]=useState(false); const [query,setQuery]=useState('');
  const [assistantOpen,setAssistantOpen]=useState(false);
  const [company,setCompany]=useState(''); const newDialog=useRef<HTMLDialogElement>(null);
  const [preview,setPreview]=useState<Document|null>(null); const previewDialog=useRef<HTMLDialogElement>(null);
  const uploadInput=useRef<HTMLInputElement>(null);
  const pathId=pathname.match(/\/(?:dossiers|agence)\/([^/]+)/)?.[1];
  const current=(pathId?cases.find(c=>c.id===pathId):pathname==='/agence'?cases.find(c=>c.id===selected&&c.status!=='draft')||cases.find(c=>c.status!=='draft'):cases.find(c=>c.id===selected))||(!pathId?cases[0]:undefined);
  const agency=pathname==='/agence'||pathname.startsWith('/agence/'); const verification=pathname.endsWith('/verification'); const preparation=pathname.endsWith('/preparation');
  const documents=pathname==='/documents'||pathname.endsWith('/documents'); const companyPage=pathname==='/entreprise'; const sourcePage=pathname==='/sources'; const list=pathname==='/dossiers';
  const rne=pathname==='/declaration'||pathname.endsWith('/declaration');
  const home=!agency&&!verification&&!preparation&&!documents&&!companyPage&&!sourcePage&&!list&&!rne;
  async function refresh(){const [cs,h,s]=await Promise.all([api<Case[]>('/cases'),api<Health>('/health'),api<Source[]>('/sources')]);setCases(cs);setHealth(h);setSources(s);}
  useEffect(()=>{let active=true;Promise.all([api<Case[]>('/cases'),api<Health>('/health'),api<Source[]>('/sources')]).then(([cs,h,s])=>{if(active){setCases(cs);setHealth(h);setSources(s);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  useEffect(()=>{setMobile(false);setError('');if(pathId)setSelected(pathId);},[pathname,pathId]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(t);},[notice]);
  const update=(c:Case)=>setCases(old=>old.some(x=>x.id===c.id)?old.map(x=>x.id===c.id?c:x):[...old,c]);
  async function action(name:string,fn:()=>Promise<void>){if(busy)return;setBusy(name);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Une erreur est survenue.');}finally{setBusy('');}}
  const openPreview=(d:Document)=>{setPreview(d);previewDialog.current?.showModal();};
  async function upload(files:FileList|File[]|null){if(!files||!current)return;await action('upload',async()=>{for(const file of Array.from(files)){const data=new FormData();data.append('file',file);update(await api<Case>(`/cases/${current.id}/documents`,{method:'POST',body:data}));}setNotice('Documents enregistrés. Ouvrez une pièce pour la vérifier ou lancez son analyse.');});if(uploadInput.current)uploadInput.current.value='';}
  const locked=!!current&&['submitted','reviewed'].includes(current.status);
  const nav=[{href:'/',label:'Vue d’ensemble',icon:House},{href:'/declaration',label:'Déclaration guidée',icon:Sparkles},{href:'/dossiers',label:'Mes dossiers',icon:FolderOpen},{href:'/documents',label:'Documents',icon:FileText},{href:'/entreprise',label:'Mon entreprise',icon:Building2}];
  const docList=(c:Case)=><div className="document-list">{c.documents.map(d=><div className="document-row" key={d.id}><button className="document-name" onClick={()=>openPreview(d)}><span className="file-icon"><FileText size={21}/></span><span><strong>{d.name}</strong><small>{d.sample?'Exemple fictif':d.content_type==='application/pdf'?'PDF':'Document'} · {d.pages.length} page{d.pages.length>1?'s':''}</small></span></button><div className="doc-actions">{d.status==='extracted'?<span className="mini-status"><Check size={13}/> {d.fields.length} champs{d.method==='manual_review'?' · relu':''}</span>:<button className="btn small secondary" disabled={!!busy||locked||agency||!health?.ai_configured} title={!health?.ai_configured?'Ouvrez la pièce pour une vérification manuelle':undefined} onClick={()=>action(d.id,async()=>{update(await api<Case>(`/cases/${c.id}/documents/${d.id}/analyze`,{method:'POST'}));setNotice('Analyse terminée. Vérifiez les champs extraits.');})}>{busy===d.id?<LoaderCircle size={14} className="spin"/>:<Sparkles size={14}/>}Analyser</button>}<button className="icon-btn" aria-label={'Ouvrir '+d.name} onClick={()=>openPreview(d)}><ArrowUpRight size={17}/></button>{documents&&!agency&&!locked&&<button className="btn small secondary" onClick={()=>openPreview(d)}>Vérifier</button>}</div></div>)}</div>;

  return <div className="app-shell">
    {mobile&&<button className="mobile-scrim" aria-label="Fermer le menu" onClick={()=>setMobile(false)}/>}
    <aside className={'sidebar '+(mobile?'open':'')}>
      <Link href="/" className="brand"><span className="brand-icon"><FileText size={24}/></span><span>Dossier<span className="brand-tn">TN</span></span></Link>
      <div className="workspace-label">VOTRE ESPACE</div>
      <nav>{nav.map(({href,label,icon:Icon})=><Link key={href} href={href} className={'nav-item '+((href==='/'?home:href==='/declaration'?rne:pathname.startsWith(href))?'active':'')}><Icon size={19}/><span>{label}</span>{href==='/dossiers'&&<span className="nav-count">{cases.length}</span>}</Link>)}</nav>
      <div className="sidebar-divider"/>
      <Link href="/sources" className={'nav-item '+(sourcePage?'active':'')}><BookOpen size={19}/>Sources officielles<ArrowUpRight size={14} className="nav-arrow"/></Link>
      <div className="sidebar-bottom"><div className="agency-switch"><ShieldCheck size={22}/><strong>De l’autre côté du dossier.</strong><p>Découvrez la revue des pièces par un agent.</p><Link href="/agence">Espace agent <ArrowRight size={15}/></Link></div><div className="profile"><span className="avatar">AT</span><div><strong>Votre espace de travail</strong><small>Prototype local</small></div></div></div>
    </aside>
    <div className="app-body">
      <header className="topbar"><div className="top-left"><button className="icon-btn mobile-toggle" aria-label="Ouvrir le menu" onClick={()=>setMobile(true)}><Menu size={22}/></button><span className="top-context">{agency?'Espace agent':'Espace entreprise'}</span><span className="top-divider">/</span><label className="company-select"><span className="sr-only">Entreprise sélectionnée</span><select value={current?.id||''} onChange={e=>{setSelected(e.target.value);if(agency)router.push(`/agence/${e.target.value}`);else if(pathId)router.push(`/dossiers/${e.target.value}/${rne?'declaration':preparation?'preparation':documents?'documents':'verification'}`);}}>{cases.map(c=><option key={c.id} value={c.id}>{c.company}</option>)}</select><ChevronDown size={14}/></label></div><div className="top-right"><span className={'mode-label '+(health?.ai_configured?'configured':'')}><span className="status-dot"/>{health?.ai_configured?'Assistant IA actif':'Vérification manuelle'}</span><span className="avatar small">AT</span></div></header>
      <main id="main-content">
        {error&&<div className="error-banner" role="alert"><CircleAlert size={18}/><span>{error}</span><button className="icon-btn" aria-label="Fermer l’erreur" onClick={()=>setError('')}><X size={16}/></button></div>}
        {loading?<div className="loading-screen"><LoaderCircle className="spin" size={28}/><p>Ouverture de votre espace…</p></div>:!current?<section className="panel"><Empty title={pathId?'Dossier introuvable':'Votre espace est prêt'} body={pathId?'Ce dossier n’existe pas dans cet espace.':'Créez votre premier dossier pour commencer.'}/><div className="panel-subsection"><button className="btn primary" onClick={()=>newDialog.current?.showModal()}><Plus size={18}/>Nouvelle démarche</button></div></section>:<>
        {!agency&&<CorrectionNotice key={current.id} c={current} onUpdate={update}/>}
        {rne&&<RneConversation key={current.id} caseId={current.id} onChanged={refresh}/>}
        {home&&<><div className="page-heading"><div><div className="eyebrow">VUE D’ENSEMBLE</div><h1>Votre prochain pas, en clair.</h1><p>Vos documents, vos démarches. Tout est au même endroit.</p></div><button className="btn primary" onClick={()=>newDialog.current?.showModal()}><Plus size={18}/>Nouvelle démarche</button></div><div className="overview-grid"><div className="main-column"><div className="metrics"><div><span>Dossiers en cours</span><strong>{cases.filter(c=>c.status!=='reviewed').length.toString().padStart(2,'0')}<FolderOpen size={21}/></strong></div><div><span>Documents réunis</span><strong>{current.documents.length.toString().padStart(2,'0')}<FileText size={21}/></strong></div><div><span>Points à confirmer</span><strong className={current.checks.open_count?'amber-text':''}>{current.checks.open_count.toString().padStart(2,'0')}<CircleAlert size={21}/></strong></div></div>
          <section className="panel case-panel"><div className="panel-heading"><div><span className="eyebrow">VOTRE DÉMARCHE</span><h2>{current.title}<span className="case-id">{current.id}</span></h2></div><Status status={current.status}/></div><Steps c={current} step={current.status==='reviewed'||current.status==='submitted'?3:current.can_submit?2:current.documents.length?1:0}/>
          {current.checks.open_count>0?<div className="action-callout"><span className="alert-icon"><CircleAlert size={22}/></span><div><strong>Des informations à vérifier</strong><p>{current.checks.open_count} point{current.checks.open_count>1?'s':''} à résoudre : informations manquantes ou contradictoires.</p></div><Link className="btn amber-btn" href={`/dossiers/${current.id}/verification`}>Vérifier <ArrowRight size={16}/></Link></div>:<div className="action-callout calm"><span className="alert-icon"><FileCheck2 size={23}/></span><div><strong>{current.status==='reviewed'?'La revue est terminée':current.can_submit?'Votre dossier peut passer à la revue':'Rassemblez les pièces de votre démarche'}</strong><p>{current.status==='reviewed'?'Retrouvez les observations et votre historique.':'Continuez la préparation et consultez les informations extraites.'}</p></div><Link className="btn primary" href={`/dossiers/${current.id}/preparation`}>Continuer <ArrowRight size={16}/></Link></div>}
          <div className="case-split"><div><div className="section-title"><h3>Documents du dossier</h3><Link href={`/dossiers/${current.id}/documents`}>Tout voir <ArrowUpRight size={14}/></Link></div>{current.documents.length?docList(current):<Empty title="Ajoutez vos premières pièces" body="PDF, images ou texte, jusqu’à 12 Mo."/>}</div><div className="company-card"><Building2 size={22}/><h3>{current.company}</h3><dl><dt>Démarche</dt><dd>Transfert du siège</dd><dt>Adresse actuelle</dt><dd>{firstFact(current,'current_address')}</dd></dl><Link href="/entreprise">Voir les informations <ArrowRight size={15}/></Link></div></div></section>
          <Link href="/sources" className="source-strip"><span className="source-strip-icon"><BookOpen size={25}/></span><div><strong>Comprendre avant de transmettre.</strong><p>Retrouvez les sources et le périmètre des vérifications.</p></div><ArrowUpRight size={20}/></Link>
          <p className="scope-note"><ShieldCheck size={14}/>{current.sample?'Dossier fictif pour explorer le parcours. ':''}La revue du prototype ne constitue pas un dépôt officiel.</p>
          </div><Assistant key={current.id} c={current} configured={!!health?.ai_configured}/></div></>}

        {verification&&<><div className="breadcrumb"><Link href="/dossiers">Mes dossiers</Link><ChevronRight size={13}/>{current.id}<ChevronRight size={13}/>Vérification</div><div className="page-heading"><div><div className="eyebrow">VÉRIFICATION DES PIÈCES</div><h1>Les détails font la différence.</h1><p>Comparez les informations à leur source, puis confirmez les écarts.</p></div><Link className="btn secondary" href={`/dossiers/${current.id}/documents`}><Plus size={17}/>Ajouter une pièce</Link></div><Steps c={current} step={1}/>
          <section className="panel verification-overview"><div className="panel-heading"><div><h2>Les informations de votre démarche</h2><p>Relisez les champs et ouvrez leurs pièces sources.</p></div><span className="count-pill">{current.checks.open_count} points à résoudre</span></div><dl className="facts-table">{current.prepared_fields.map(field=><div key={field.key}><dt>{field.label}</dt><dd>{firstFact(current,field.key)}<span className={'badge '+(field.state==='confirmed'?'green':field.state==='conflict'||field.state==='missing'?'amber':'neutral')}>{({confirmed:'Déclaré / confirmé',extracted:'À relire',missing:'Non renseigné',conflict:'Écart détecté'})[field.state]}</span>{field.evidence.map((e,i)=><button className="field-source" key={i} onClick={()=>{const doc=current.documents.find(d=>d.id===e.document_id);if(doc)openPreview(doc);}}><FileText size={12}/>{e.document_name} · p. {e.page}<ArrowUpRight size={12}/></button>)}</dd></div>)}</dl></section>
          {current.checks.issues.map(issue=><IssuePanel key={current.id+issue.key} issue={issue} c={current} locked={locked} busy={!!busy} preview={openPreview} onConfirm={value=>action('confirm',async()=>{update(await api<Case>(`/cases/${current.id}/confirm`,{method:'POST',body:JSON.stringify({key:issue.key,value})}));setNotice('Confirmation enregistrée. Les pièces originales sont conservées.');})}/>)}
          {!current.checks.issues.length&&<div className="panel"><Empty title={current.documents.length?'Aucun écart détecté dans les champs extraits':'Aucune pièce à comparer'} body="Ce résultat porte sur les contrôles disponibles. Il ne garantit pas la complétude du dossier."/></div>}
          {current.checks.pending_documents.length>0&&<div className="action-callout"><CircleAlert size={21}/><div><strong>{current.checks.pending_documents.length} document(s) restent à vérifier</strong><p>Ouvrez les pièces pour une vérification manuelle ou une analyse IA.</p></div><Link href={`/dossiers/${current.id}/documents`} className="btn secondary">Documents <ArrowRight size={15}/></Link></div>}
          <div className="bottom-actions"><p><ShieldCheck size={16}/>Les confirmations restent visibles dans l’historique.</p><Link href={`/dossiers/${current.id}/preparation`} className="btn primary">Préparer le dossier <ArrowRight size={16}/></Link></div></>}

        {documents&&<><div className="page-heading"><div><div className="eyebrow">VOS PIÈCES</div><h1>Chaque document, à sa place.</h1><p>Ajoutez les pièces de {current.company} et retrouvez leur contenu.</p></div></div><div className="documents-layout"><section className="panel"><div className="panel-heading"><h2>Documents du dossier</h2><span className="count-pill">{current.documents.length} pièces</span></div>{docList(current)}<input ref={uploadInput} className="sr-only" type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.txt" aria-label="Ajouter des documents" onChange={e=>upload(e.target.files)} disabled={locked||!!busy}/><button className="upload-zone" disabled={locked||!!busy} onClick={()=>uploadInput.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!locked&&!busy)upload(e.dataTransfer.files);}}>{busy==='upload'?<LoaderCircle className="spin" size={30}/>:<UploadCloud size={30}/>}<strong>{locked?'Dossier en revue':'Déposez vos documents ici'}</strong><span>{locked?'Les modifications sont suspendues pendant la revue.':'ou cliquez pour parcourir vos fichiers'}</span><small>PDF, PNG, JPEG, TXT · 12 Mo · 12 pages maximum</small></button></section><aside className="panel help-panel"><Sparkles size={25}/><h3>Des informations que vous pouvez vérifier.</h3><p>L’analyse propose des champs liés à leur texte d’origine. Vous gardez la main sur les confirmations.</p><div className="help-step"><span>1</span>Ajoutez une pièce</div><div className="help-step"><span>2</span>Vérifiez ses champs ou lancez l’analyse</div><div className="help-step"><span>3</span>Vérifiez les informations</div>{!health?.ai_configured&&<div className="soft-note">Ouvrez une pièce et recopiez ses champs pour continuer sans IA. L’analyse automatique peut être activée avec Azure.</div>}<Link href={`/dossiers/${current.id}/verification`} className="btn primary">Ouvrir la vérification <ArrowRight size={16}/></Link></aside></div></>}

        {preparation&&<><div className="breadcrumb"><Link href="/dossiers">Mes dossiers</Link><ChevronRight size={13}/>{current.id}<ChevronRight size={13}/>Préparation</div><div className="page-heading"><div><div className="eyebrow">PRÉPARATION DU DOSSIER</div><h1>Prêt pour un dernier regard.</h1><p>Relisez les informations avant de transmettre à la revue locale.</p></div><a className="btn secondary" href={`/api/cases/${current.id}/export`}><ArrowDownToLine size={17}/>Télécharger le dossier</a></div><Steps c={current} step={2}/><div className="documents-layout"><section className="panel"><div className="panel-heading"><h2>{current.company}</h2><Status status={current.status}/></div><dl className="facts-table">{Object.keys(fieldNames).map(key=><div key={key}><dt>{fieldNames[key]}</dt><dd>{firstFact(current,key)}{current.confirmations[key]&&<span className="inline-verified"><Check size={13}/>Confirmé</span>}</dd></div>)}</dl><div className="panel-subsection draft-download"><FileText size={26}/><div><h3>Votre brouillon de changement d’adresse</h3><p>Une fiche imprimable avec les valeurs, les passages sources et les points à compléter.</p><a className="text-link" href={`/api/cases/${current.id}/draft`}><ArrowDownToLine size={15}/>Télécharger le brouillon</a></div></div><div className="panel-subsection"><h3>Pièces à examiner</h3>{docList(current)}</div></section><aside className="panel help-panel"><FileCheck2 size={28}/><h3>Transmettre à la revue</h3><p>Un agent pourra consulter vos pièces et les confirmations enregistrées.</p><div className="check-line"><Check size={17}/>{current.documents.length} pièces réunies</div><div className="check-line">{current.checks.open_count?<CircleAlert size={17}/>:<Check size={17}/>}{current.checks.open_count} point(s) à résoudre</div><div className="check-line"><Clock3 size={17}/>{current.checks.pending_documents.length} pièce(s) à vérifier</div><div className="soft-note">Contrôles de cohérence uniquement. La liste complète des pièces réglementaires n’est pas encore validée. Aucun dépôt officiel n’est effectué.</div><button className="btn primary" disabled={!!busy||!current.can_submit||locked} onClick={()=>action('submit',async()=>{update(await api<Case>(`/cases/${current.id}/submit`,{method:'POST'}));setNotice('Dossier transmis à l’espace de revue local.');})}>{busy==='submit'?<LoaderCircle className="spin" size={17}/>:<Send size={16}/>}Transmettre à la revue</button>{locked&&<Link href={`/agence/${current.id}`} className="text-link">Consulter la revue <ArrowRight size={15}/></Link>}</aside></div></>}

        {agency&&<><div className="page-heading"><div><div className="eyebrow">ESPACE AGENT · SIMULATION</div><h1>Les bonnes pièces. Les bons détails.</h1><p>Examinez le dossier et ses confirmations sans ressaisir les informations.</p></div><button className="btn secondary" disabled={!!busy} onClick={()=>action('refresh',refresh)}><Clock3 size={16}/>Actualiser</button></div><div className="review-layout"><section className="panel queue"><div className="panel-heading"><h3>File de revue</h3><span className="count-pill">{cases.filter(c=>c.status!=='draft').length}</span></div>{cases.filter(c=>c.status!=='draft').map(c=><button className={'queue-item '+(c.id===current.id?'selected':'')} key={c.id} onClick={()=>{setSelected(c.id);router.push(`/agence/${c.id}`);}}><strong>{c.company}</strong><small>{c.id} · {c.title}</small><Status status={c.status}/></button>)}{cases.every(c=>c.status==='draft')&&<Empty title="Aucun dossier transmis" body="Terminez la vérification côté entreprise, puis transmettez le dossier."/>}</section>{current.status==='draft'?<section className="panel"><Empty title="Sélectionnez un dossier transmis" body="Les dossiers en préparation restent dans l’espace entreprise."/></section>:<><section className="panel review-case"><div className="panel-heading"><div><span className="eyebrow">{current.id}</span><h2>{current.company}</h2></div></div><h3>{current.title}</h3><div className="address-transition"><div><small>Adresse actuelle</small><strong>{firstFact(current,'current_address')}</strong></div><ArrowRight size={20}/><div><small>Adresse proposée</small><strong>{firstFact(current,'new_address')}</strong></div></div><h3>Pièces fournies</h3>{docList(current)}<h3 className="space-top">Confirmations de l’entreprise</h3>{Object.entries(current.confirmations).map(([key,value])=><div className="confirmed-row" key={key}><CheckCheck size={20}/><div><strong>{fieldNames[key]||key}</strong><p>{value.value}</p><small>{date(value.at)} · Valeur déclarée, originaux conservés</small></div></div>)}{!Object.keys(current.confirmations).length&&<p className="muted">Aucune confirmation enregistrée.</p>}<Link className="text-link" href="/sources">Consulter les sources et les limites <ArrowUpRight size={15}/></Link></section><ReviewPanel key={current.id} c={current} busy={!!busy} onReview={(reviewAction,note)=>action('review',async()=>{update(await api<Case>(`/cases/${current.id}/review`,{method:'POST',body:JSON.stringify({action:reviewAction,note})}));setNotice('La décision de revue a été enregistrée.');})}/></>}</div></>}

        {list&&<><div className="page-heading"><div><div className="eyebrow">VOS DÉMARCHES</div><h1>Une vue sur chaque dossier.</h1><p>Retrouvez les pièces, les confirmations et le suivi de vos demandes.</p></div><button className="btn primary" onClick={()=>newDialog.current?.showModal()}><Plus size={18}/>Nouvelle démarche</button></div><section className="panel"><div className="panel-heading"><h2>Mes dossiers</h2><label className="search-input"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un dossier…" aria-label="Rechercher un dossier"/></label></div><div className="case-list">{cases.filter(c=>(c.company+c.id+c.title).toLowerCase().includes(query.toLowerCase())).map(c=><Link href={`/dossiers/${c.id}/verification`} className="case-list-row" key={c.id}><span className="case-list-icon"><FolderOpen size={24}/></span><div><strong>{c.company}</strong><p>{c.title} <span>· {c.id}</span></p></div><span className="muted">{c.documents.length} pièces</span><Status status={c.status}/><ChevronRight size={18}/></Link>)}</div></section></>}

        {companyPage&&<><div className="page-heading"><div><div className="eyebrow">MON ENTREPRISE</div><h1>Vos informations, à la source.</h1><p>Les champs ci-dessous proviennent des pièces de {current.company}.</p></div></div><section className="panel"><div className="panel-heading"><h2>{current.company}</h2>{current.sample&&<span className="badge neutral">Données fictives</span>}</div><dl className="facts-table">{Object.entries(fieldNames).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{firstFact(current,key)}{current.confirmations[key]&&<span className="inline-verified"><Check size={13}/>Confirmé</span>}</dd></div>)}</dl><div className="panel-subsection"><Link className="btn primary" href={`/dossiers/${current.id}/verification`}>Vérifier les pièces <ArrowRight size={16}/></Link></div></section></>}

        {sourcePage&&<><div className="page-heading"><div><div className="eyebrow">LES RÉFÉRENCES DU DOSSIER</div><h1>Une source derrière chaque étape.</h1><p>Consultez les références publiques sélectionnées pour ce prototype.</p></div></div><div className="source-notice"><BookOpen size={23}/><div><strong>Un périmètre volontairement limité.</strong><p>Ces notes identifient les références. Elles ne constituent pas un corpus juridique exhaustif. La liste détaillée des pièces à fournir reste à vérifier.</p></div></div><div className="source-cards">{sources.map((s,i)=><article className="panel source-card" key={s.id}><div className="source-index">{String(i+1).padStart(2,'0')}</div><span className="eyebrow">{s.type}</span><h2>{s.title}</h2><p>{s.text}</p><div><small>Référence consultée le {s.checked_at}</small><a href={s.url} target="_blank" rel="noreferrer" className="text-link">Ouvrir la source <ArrowUpRight size={15}/></a></div></article>)}</div></>}
        </>}
      </main>
    </div>
    <dialog ref={newDialog} className="modal"><form onSubmit={e=>{e.preventDefault();action('create',async()=>{const c=await api<Case>('/cases',{method:'POST',body:JSON.stringify({company})});update(c);setSelected(c.id);setCompany('');newDialog.current?.close();router.push(`/dossiers/${c.id}/declaration`);});}}><div className="modal-heading"><span className="brand-icon"><FolderOpen size={23}/></span><button type="button" className="icon-btn" aria-label="Fermer" onClick={()=>newDialog.current?.close()}><X size={20}/></button></div><h2>Une nouvelle démarche.</h2><p>Commencez un dossier de changement d’adresse pour votre entreprise.</p><label className="form-label">Démarche<select defaultValue="address_change"><option value="address_change">Changement d’adresse — transfert du siège</option></select></label><label className="form-label">Nom de l’entreprise<input required minLength={2} maxLength={120} value={company} onChange={e=>setCompany(e.target.value)} placeholder="Ex. Jasmin Services SARL"/></label><div className="soft-note"><strong>Votre parcours</strong><br/>Conversation guidée → CIN et informations → confirmation → formulaire RNE F005.</div><div aria-live="polite">{error&&<p className="assistant-error">{error}</p>}</div><button className="btn primary full" disabled={!!busy||company.trim().length<2}>{busy==='create'?<LoaderCircle className="spin" size={17}/>:<Plus size={17}/>}Créer le dossier</button></form></dialog>
    <dialog ref={previewDialog} className="modal document-modal"><div className="modal-heading"><div><span className="eyebrow">PIÈCE DU DOSSIER</span><h2>{preview?.name}</h2></div><button className="icon-btn" aria-label="Fermer le document" onClick={()=>previewDialog.current?.close()}><X size={21}/></button></div>{preview&&current&&<><div className="preview-toolbar"><span>{preview.sample?'Document fictif · démonstration':'Texte extrait · à vérifier avec l’original'}</span><a href={`/api/cases/${current.id}/documents/${preview.id}/file`} target="_blank" rel="noreferrer" className="text-link">Ouvrir l’original <ArrowUpRight size={16}/></a></div>{preview.text?<div className="document-pages">{preview.pages.map(p=><section key={p.page}><small>Page {p.page}</small><pre className="document-text" dir="auto">{p.text||'Page scannée : consultez l’original.'}</pre></section>)}</div>:<Empty title="Aucun texte extrait" body="Ouvrez l’original ou lancez l’analyse du document."/>}<h3>Informations extraites</h3><dl className="facts-table">{preview.fields.map((f,i)=><div key={i}><dt>{fieldNames[f.key]}</dt><dd>{f.value}<small className="field-evidence">Page {f.page} · {f.evidence}</small></dd></div>)}</dl>{!agency&&<DocumentReview key={current.id+preview.id} c={current} document={preview} locked={locked} onSave={updated=>{update(updated);setPreview(updated.documents.find(d=>d.id===preview.id)||null);}}/>}</>}</dialog>
    {current&&!home&&!rne&&<div className="floating-assistant">{assistantOpen&&<div id="context-assistant"><button className="assistant-close icon-btn" aria-label="Fermer l’assistant" onClick={()=>setAssistantOpen(false)}><X size={18}/></button><Assistant key={current.id} c={current} configured={!!health?.ai_configured}/></div>}<button className="btn primary" aria-expanded={assistantOpen} aria-controls="context-assistant" onClick={()=>setAssistantOpen(!assistantOpen)}><Sparkles size={17}/>{assistantOpen?'Masquer l’assistant':'Un coup de main ?'}</button></div>}
    {notice&&<div className="toast" role="status"><Check size={18}/>{notice}</div>}
  </div>;
}

function IssuePanel({issue,c,locked,busy,onConfirm,preview}:{issue:Issue;c:Case;locked:boolean;busy:boolean;onConfirm:(value:string)=>void;preview:(d:Document)=>void}){
  const [value,setValue]=useState(issue.confirmation?.value||issue.evidence.at(-1)?.value||'');
  return <section className={'issue-block '+(issue.resolved?'resolved':'')}><div className="issue-banner">{issue.resolved?<CheckCheck size={20}/>:<CircleAlert size={20}/>}<span><strong>{issue.label}</strong> — {issue.resolved?'La valeur confirmée est conservée avec les pièces originales.':issue.type==='missing'?'Cette information manque pour préparer le brouillon.':'Les pièces indiquent des valeurs différentes pour ce même champ.'}</span></div><div className="comparison-layout"><div className="evidence-grid">{issue.type==='missing'&&<div className="panel missing-field"><FileText size={28}/><h3>{issue.label} à compléter</h3><p>Ajoutez cette information depuis une pièce, ou déclarez la valeur ci-contre. Une déclaration sans passage source sera indiquée dans le brouillon.</p><Link className="btn secondary" href={`/dossiers/${c.id}/documents`}>Vérifier les documents <ArrowRight size={15}/></Link></div>}{issue.evidence.map((e,i)=><article className="evidence-viewer" key={e.document_id+'-'+i}><div className="evidence-toolbar"><FileText size={18}/><strong>{e.document_name}</strong><span>Page {e.page}</span></div><div className="paper"><div className="paper-top">{c.sample?'EXEMPLE FICTIF':'PASSAGE DU DOCUMENT'}<span>0{i+1}</span></div><h3>{c.company}</h3><div className="paper-rule"/><div className="paper-title">{e.document_name}</div><p className="paper-label">{issue.label}</p><mark dir="auto">{e.value}</mark><blockquote dir="auto">{e.evidence}</blockquote><button className="text-link" onClick={()=>{const d=c.documents.find(d=>d.id===e.document_id);if(d)preview(d);}}>Voir le document complet <ArrowUpRight size={15}/></button></div></article>)}</div><form className="panel confirm-panel" onSubmit={e=>{e.preventDefault();onConfirm(value);}}><span className={'badge '+(issue.resolved?'green':'amber')}>{issue.resolved?<Check size={13}/>:<Sparkles size={13}/>} {issue.resolved?'Confirmation enregistrée':'À confirmer'}</span><h3>Vous avez le dernier mot.</h3><p>{issue.type==='missing'?'Renseignez la valeur à déclarer, ou vérifiez une pièce pour ajouter un passage source.':'Vérifiez les passages avant de choisir la valeur à retenir.'}</p>{issue.evidence.map((e,i)=><button type="button" disabled={locked||busy} className={'choice '+(value===e.value?'chosen':'')} key={i} onClick={()=>setValue(e.value)}><span className="radio-circle"/><span>{e.value}</span></button>)}<label className="form-label">Valeur à retenir<input required value={value} onChange={e=>setValue(e.target.value)} maxLength={500} disabled={locked||busy}/></label><button className="btn primary full" disabled={locked||busy}><Check size={16}/>{issue.resolved?'Mettre à jour':'Confirmer la valeur'}</button><small className="confirmation-note"><ShieldCheck size={14}/>Les originaux restent inchangés. Votre confirmation est ajoutée au dossier.</small></form></div></section>;
}

function ReviewPanel({c,busy,onReview}:{c:Case;busy:boolean;onReview:(action:string,note:string)=>void}){
  const [note,setNote]=useState('');
  return <aside className="panel review-actions"><h3>Revue du dossier</h3><Status status={c.status}/><label className="form-label">Votre observation<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Précisez les éléments à corriger ou votre observation…" rows={4} maxLength={2000}/></label><button className="btn secondary full" disabled={busy||c.status!=='submitted'||!note.trim()} onClick={()=>onReview('request_correction',note)}><CircleAlert size={16}/>Demander une correction</button><button className="btn primary full" disabled={busy||c.status!=='submitted'} onClick={()=>onReview('reviewed',note)}><CheckCheck size={17}/>Marquer comme examiné</button><div className="review-divider"/><h3>Historique du dossier</h3><div className="timeline">{[...c.events].reverse().map((e,i)=><div className="timeline-item" key={e.id}><span className={'timeline-icon '+(i===0?'latest':'')}><Check size={11}/></span><div><strong>{e.label}</strong><small>{date(e.at)} · {e.actor}</small>{e.detail&&<p>{e.detail}</p>}</div></div>)}</div></aside>;
}

function Assistant({c,configured}:{c:Case;configured:boolean}){
  const [question,setQuestion]=useState('');const [loading,setLoading]=useState(false);const [answer,setAnswer]=useState('');const [sources,setSources]=useState<Source[]>([]);const [error,setError]=useState('');
  async function ask(text:string){if(!text.trim()||loading)return;setQuestion(text);setLoading(true);setError('');try{const result=await api<{text:string;sources:Source[]}>(`/cases/${c.id}/assistant`,{method:'POST',body:JSON.stringify({question:text})});setAnswer(result.text);setSources(result.sources);}catch(e){setError(e instanceof Error?e.message:'Réponse indisponible.');}finally{setLoading(false);}}
  return <aside className="panel assistant-panel"><div className="assistant-heading"><span className="assistant-icon"><Sparkles size={20}/></span><div><h3>Un coup de main ?</h3><small>{configured?'Assistant Azure':'Guide du parcours'}</small></div></div><div className="assistant-body"><div className="assistant-intro"><MessageCircle size={22}/><p>Comprenez votre prochaine étape, avec les sources à portée de main.</p></div><span className="eyebrow">POUR CE DOSSIER</span>{['Pourquoi vérifier cette adresse ?','Quelle est la prochaine étape ?','Quelles sont les limites du contrôle ?'].map(text=><button className="prompt-chip" key={text} disabled={loading} onClick={()=>ask(text)}>{text}<ArrowUpRight size={14}/></button>)}{loading&&<div className="assistant-answer"><LoaderCircle size={18} className="spin"/>Recherche dans les références…</div>}{error&&<p className="assistant-error" role="alert">{error}</p>}{answer&&<div className="assistant-answer" dir="auto">{answer}{sources.map(s=><a href={s.url} target="_blank" rel="noreferrer" key={s.id}>{s.title}<ArrowUpRight size={13}/></a>)}</div>}</div><div className="assistant-footer"><form onSubmit={e=>{e.preventDefault();ask(question);}}><label className="sr-only" htmlFor="assistant-question">Votre question</label><input id="assistant-question" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Posez votre question…" maxLength={2000}/><button type="submit" disabled={loading||!question.trim()} aria-label="Envoyer la question"><Send size={17}/></button></form><p><BookOpen size={12}/>{configured?'Réponses fondées sur les références disponibles.':'Azure non configuré · aucune réponse LLM.'}</p></div></aside>;
}
